import { StoresFilterFormValues } from "./schema";

export const defaultValues: StoresFilterFormValues = {
  idStore: [],
  idCity: [],
  idRegion: [],
  idManager: [],
  ageGroup: [],
  channel: [],
  storeCondition: [],
  nightStore: null,
  shopOnAuto: null,
  deliveryIm: null,
  walkingDelivery: null,
  grill: null,
  dopeki: null,
  bakehouse: null,
  brazier: null,
  camera: null,
  coffee: null,
  typeCoffee: [],
  ownershipCoffee: [],
  milkRefrigerator: null,
  pizzaCm: [],
  pizzaDaysSchedule: [],
  pizzaHoursSchedule: [],
  maxPower: [],
  format: [],
  discountTime: [],
};
