import {
  BarChart3,
  BookOpen,
  Briefcase,
  ClipboardList,
  FileText,
  Globe,
  PieChart,
  Store,
  Table2,
} from "lucide-react";

export const EXTERNAL_RESOURCES = [
  {
    title: "Аудиты",
    url: "https://datalens.ru/b5n0k2es0je2x-audity-frs",
    source: "DataLens",
    category: "Аналитика",
    icon: BarChart3,
  },
  {
    title: "Покрытие полочного пространства",
    url: "https://app.powerbi.com/view?r=eyJrIjoiZTZmMDI3ODMtNjI0Mi00OTY1LWE5MTctNTRmZDk0ZmY4ZjNlIiwidCI6IjJiZWEzNTBjLTUwOTctNDQ1NC1hMmNkLTY5ODA4YjJhNDg1ZSJ9",
    source: "Power BI",
    category: "Аналитика",
    icon: PieChart,
  },
  {
    title: "Ночные магазины",
    url: "https://app.powerbi.com/view?r=eyJrIjoiNDZlNTRhZDAtMmUzNi00YWJmLWE4NTYtN2JmZmE4ZGRmYmI0IiwidCI6IjJiZWEzNTBjLTUwOTctNDQ1NC1hMmNkLTY5ODA4YjJhNDg1ZSJ9",
    source: "Power BI",
    category: "Аналитика",
    icon: PieChart,
  },
  {
    title: "Экран проблем",
    url: "https://docs.google.com/spreadsheets/d/1u3h6kC-dHORx1oy5Ke3ZmZvbW4WD9sZwJWbhoQiKURw/edit?gid=1405042014#gid=1405042014",
    source: "Google Таблицы",
    category: "Сервисы",
    icon: Table2,
  },
  {
    title: "Бриф для дизайнера",
    url: "https://franchise.kalina-malina.ru/catalog_km#rec2161265371",
    source: "Франчайзинг",
    category: "Сервисы",
    icon: Store,
  },
  {
    title: "Каталог мероприятий (маркетинг)",
    url: "https://franchise.kalina-malina.ru/catalog_km",
    source: "Франчайзинг",
    category: "Сервисы",
    icon: Store,
  },
  {
    title: "Битрикс24",
    url: "https://www.bitrix24.ru/prices/?utm_source=yandex&utm_medium=cpc&utm_campaign=ru_brand_tovarnaya&utm_content=keys_5491424048%7Ccid%7C114231842%7Caid%7C---autotargeting%7C53011605547%7Csrc&utm_term=---autotargeting&etext=2202.3Mcjnl2WZBZLO7rMU08XfvnnKPc051ffAc6UguECXbJ4emlramxjcHJwcnFwZHFm.e1d9af5a7dea20cef58a3450db6d00e45a9b5fc9&yclid=16677198276915363839&ybaip=1",
    source: "Битрикс24",
    category: "Сервисы",
    icon: Briefcase,
  },
  {
    title: "Обучение в Битрикс24 «Как работать в календаре Коллабы»",
    url: "https://helpdesk.bitrix24.ru/open/22707772?SOURCE_LINK_PLACE=ARTICLE_DETAIL&ANCHOR=null",
    source: "Битрикс24",
    category: "Обучение",
    icon: BookOpen,
  },
  {
    title: "Структура сотрудников сопутствующих товаров",
    url: "https://docs.google.com/spreadsheets/d/1O4n6ZkWN3ObnEvrYv6ugmTW9j5RQszDB/edit?gid=1681098189#gid=1681098189",
    source: "Google Таблицы",
    category: "Сервисы",
    icon: Table2,
  },
  {
    title: "NPS",
    url: "https://app.powerbi.com/view?r=eyJrIjoiNGI0NGM1ZmYtZGIwYS00MmY3LWI3MDgtYjE5NzE3MDRjNTU3IiwidCI6IjJiZWEzNTBjLTUwOTctNDQ1NC1hMmNkLTY5ODA4YjJhNDg1ZSJ9",
    source: "Power BI",
    category: "Аналитика",
    icon: PieChart,
  },
  {
    title: "Бронирование ТМЦ на мероприятия",
    url: "https://docs.google.com/spreadsheets/d/17vJ1L6LU95V9wfDbOYiE9yBDMNxY7mP3gLTkZeLNAGY/edit?gid=826119512#gid=826119512",
    source: "Google Таблицы",
    category: "Сервисы",
    icon: Table2,
  },
  {
    title: "SKU",
    url: "https://app.powerbi.com/view?r=eyJrIjoiZDk2NjRjM2QtNWM2Yi00MDgzLTkyMGEtOWJhNWQyNzIzNjdmIiwidCI6IjJiZWEzNTBjLTUwOTctNDQ1NC1hMmNkLTY5ODA4YjJhNDg1ZSJ9",
    source: "Power BI",
    category: "Аналитика",
    icon: PieChart,
  },
  {
    title: "Проверка кандидата",
    url: "https://b24-cuzaqj.bitrix24site.ru/crm_form_zufoe/",
    source: "Битрикс24",
    category: "Сервисы",
    icon: Briefcase,
  },
  {
    title: "Запрос по корректировке заказа от партнера/магазина",
    url: "https://docs.google.com/forms/d/e/1FAIpQLSe4Lnrt6KCnQQsr7Xe4NHDl6gLo3ta56uIHsmyFYSz2FHrv9A/viewform",
    source: "Google Формы",
    category: "Автозаказ",
    icon: ClipboardList,
  },
  {
    title: "Запрос по корректировке заказа (Ответы)",
    url: "https://docs.google.com/spreadsheets/d/1EBoyWDx2MHsEopDdF0DNKJkKOgU6HRr498zfmJZ1lxs/edit?resourcekey=&gid=1885801896#gid=1885801896",
    source: "Google Таблицы",
    category: "Автозаказ",
    icon: Table2,
  },
  {
    title: "Краткая инструкция для настройки фильтров в режиме чтения",
    url: "https://docs.google.com/document/d/1zO1LSGCqxrbhx56yJC6V9vICnaL-VHmUjwR-V0QUL5U/edit?tab=t.0#heading=h.fxw6zmde0h28",
    source: "Google Документы",
    category: "Автозаказ",
    icon: FileText,
  },
  {
    title: "ЧЗ — возможные проблемы и их решение",
    url: "https://docs.google.com/document/d/1Nz1MVc8Mw8ORY6o9ZQJjNgJLvs6MgHkT/edit#heading=h.pskr20qlrx5i",
    source: "Google Документы",
    category: "Обучение",
    icon: BookOpen,
  },
  {
    title:
      "Что делать, если на магазине не работает или некорректно работает видеонаблюдение",
    url: "https://docs.google.com/document/d/19P7LNh0E-JZ2Qu1k8isErIp9Z5xUh5Ua/edit",
    source: "Google Документы",
    category: "Обучение",
    icon: BookOpen,
  },
  {
    title: "Сроки годности на магазине",
    url: "http://10.32.2.182:8001",
    source: "Сайт",
    category: "Сервисы",
    icon: Globe,
  },
];
