export interface FullThemePreset {
  id: string;
  name: string;
  description: string;
  light: {
    colors: Record<string, string>;
    radius: string;
    shadowX: string;
    shadowY: string;
    shadowBlur: string;
    shadowSpread: string;
    shadowOpacity: string;
    trackingNormal: string;
  };
  dark: {
    colors: Record<string, string>;
    radius: string;
    shadowX: string;
    shadowY: string;
    shadowBlur: string;
    shadowSpread: string;
    shadowOpacity: string;
    trackingNormal: string;
  };
}

export const FULL_THEME_PRESETS: FullThemePreset[] = [
  {
    id: "default",
    name: "Стандартная",
    description: "Классическая тема приложения",
    light: {
      colors: {
        background: "#ffffff",
        foreground: "#333333",
        card: "#fafafa",
        cardForeground: "#333333",
        popover: "#ffffff",
        popoverForeground: "#333333",
        primary: "#e50046",
        primaryForeground: "#ebe8fc",
        secondary: "#ffadc6",
        secondaryForeground: "#e50046",
        muted: "#ebebea",
        mutedForeground: "#acaaa7",
        accent: "#e50046",
        accentForeground: "#ebe8fc",
        destructive: "#e50046",
        destructiveForeground: "#fbe9eb",
        positive: "#249742",
        positiveForeground: "#a0e5b3",
        average: "#d35d0e",
        averageForeground: "#fca258",
        height: "#d3a304",
        heightForeground: "#e7d153",
        border: "#dad9d8",
        input: "#dad9d8",
        ring: "#ffadc6",
        chart1: "347 77% 50%",
        chart2: "352 83% 91%",
        chart3: "350 80% 72%",
        chart4: "351 83% 82%",
        chart5: "349 77% 62%",
      },
      radius: "0.625rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "3px",
      shadowSpread: "0px",
      shadowOpacity: "0.1",
      trackingNormal: "0px",
    },
    dark: {
      colors: {
        background: "#191919",
        foreground: "#d4d4d4",
        card: "#262626",
        cardForeground: "#d4d4d4",
        popover: "#191919",
        popoverForeground: "#d4d4d4",
        primary: "#e50046",
        primaryForeground: "#ebe8fc",
        secondary: "#ffadc6",
        secondaryForeground: "#e50046",
        muted: "#262626",
        mutedForeground: "#636363",
        accent: "#e50046",
        accentForeground: "#ebe8fc",
        destructive: "#ad413f",
        destructiveForeground: "#fbe9eb",
        positive: "#34a853",
        positiveForeground: "#d8f3df",
        average: "#d35d0e",
        averageForeground: "#fca258",
        height: "#e2ae01",
        heightForeground: "#fff2aa",
        border: "#2f2f2f",
        input: "#2f2f2f",
        ring: "#ffadc6",
        chart1: "347 77% 50%",
        chart2: "352 83% 91%",
        chart3: "350 80% 72%",
        chart4: "351 83% 82%",
        chart5: "349 77% 62%",
      },
      radius: "0.625rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "3px",
      shadowSpread: "0px",
      shadowOpacity: "0.1",
      trackingNormal: "0px",
    },
  },
  {
    id: "nature",
    name: "Природа",
    description: "Натуральные зеленые и земляные тона",
    light: {
      colors: {
        background: "#f5f5dc",
        foreground: "#2d4a2b",
        card: "#ffffff",
        cardForeground: "#2d4a2b",
        popover: "#ffffff",
        popoverForeground: "#2d4a2b",
        primary: "#4a7c59",
        primaryForeground: "#ffffff",
        secondary: "#8b7355",
        secondaryForeground: "#ffffff",
        muted: "#e8e5d7",
        mutedForeground: "#5a6a58",
        accent: "#7fa650",
        accentForeground: "#ffffff",
        destructive: "#8b4513",
        destructiveForeground: "#ffffff",
        positive: "#5a9367",
        positiveForeground: "#ffffff",
        average: "#d4a574",
        averageForeground: "#2d4a2b",
        height: "#6b8e9e",
        heightForeground: "#ffffff",
        border: "#a8a080",
        input: "#ffffff",
        ring: "#4a7c59",
        chart1: "#4a7c59",
        chart2: "#8b7355",
        chart3: "#7fa650",
        chart4: "#5a9367",
        chart5: "#6b8e9e",
      },
      radius: "0.75rem",
      shadowX: "0px",
      shadowY: "3px",
      shadowBlur: "12px",
      shadowSpread: "0px",
      shadowOpacity: "0.15",
      trackingNormal: "0.01em",
    },
    dark: {
      colors: {
        background: "#1a2318",
        foreground: "#d5e5d3",
        card: "#243322",
        cardForeground: "#d5e5d3",
        popover: "#243322",
        popoverForeground: "#d5e5d3",
        primary: "#6fa87d",
        primaryForeground: "#1a2318",
        secondary: "#a88968",
        secondaryForeground: "#1a2318",
        muted: "#2a3928",
        mutedForeground: "#a5b5a3",
        accent: "#95c070",
        accentForeground: "#1a2318",
        destructive: "#b5694d",
        destructiveForeground: "#ffffff",
        positive: "#7ab587",
        positiveForeground: "#1a2318",
        average: "#e5c59a",
        averageForeground: "#1a2318",
        height: "#8ba5b5",
        heightForeground: "#1a2318",
        border: "#3a4938",
        input: "#243322",
        ring: "#6fa87d",
        chart1: "#6fa87d",
        chart2: "#a88968",
        chart3: "#95c070",
        chart4: "#7ab587",
        chart5: "#8ba5b5",
      },
      radius: "0.75rem",
      shadowX: "0px",
      shadowY: "3px",
      shadowBlur: "12px",
      shadowSpread: "0px",
      shadowOpacity: "0.25",
      trackingNormal: "0.01em",
    },
  },
  {
    id: "retro",
    name: "Ретро",
    description: "Винтажные цвета 70-х годов",
    light: {
      colors: {
        background: "#f9f4e8",
        foreground: "#3e2723",
        card: "#fff9e6",
        cardForeground: "#3e2723",
        popover: "#fff9e6",
        popoverForeground: "#3e2723",
        primary: "#d4732f",
        primaryForeground: "#ffffff",
        secondary: "#c99351",
        secondaryForeground: "#ffffff",
        muted: "#efe8db",
        mutedForeground: "#6d5d4b",
        accent: "#8c5e42",
        accentForeground: "#ffffff",
        destructive: "#a84f3e",
        destructiveForeground: "#ffffff",
        positive: "#7a9d54",
        positiveForeground: "#ffffff",
        average: "#d49748",
        averageForeground: "#ffffff",
        height: "#6b7fa6",
        heightForeground: "#ffffff",
        border: "#b8a88f",
        input: "#fff9e6",
        ring: "#d4732f",
        chart1: "#d4732f",
        chart2: "#c99351",
        chart3: "#8c5e42",
        chart4: "#7a9d54",
        chart5: "#6b7fa6",
      },
      radius: "0.375rem",
      shadowX: "3px",
      shadowY: "3px",
      shadowBlur: "6px",
      shadowSpread: "0px",
      shadowOpacity: "0.2",
      trackingNormal: "0.02em",
    },
    dark: {
      colors: {
        background: "#2a1f1a",
        foreground: "#f0e5d8",
        card: "#3a2f2a",
        cardForeground: "#f0e5d8",
        popover: "#3a2f2a",
        popoverForeground: "#f0e5d8",
        primary: "#e89b67",
        primaryForeground: "#2a1f1a",
        secondary: "#d4a86d",
        secondaryForeground: "#2a1f1a",
        muted: "#3d332c",
        mutedForeground: "#c4b4a4",
        accent: "#ab7a5c",
        accentForeground: "#ffffff",
        destructive: "#c76d5c",
        destructiveForeground: "#ffffff",
        positive: "#96b570",
        positiveForeground: "#2a1f1a",
        average: "#e5b364",
        averageForeground: "#2a1f1a",
        height: "#899cbe",
        heightForeground: "#ffffff",
        border: "#5a4f44",
        input: "#3a2f2a",
        ring: "#e89b67",
        chart1: "#e89b67",
        chart2: "#d4a86d",
        chart3: "#ab7a5c",
        chart4: "#96b570",
        chart5: "#899cbe",
      },
      radius: "0.375rem",
      shadowX: "3px",
      shadowY: "3px",
      shadowBlur: "6px",
      shadowSpread: "0px",
      shadowOpacity: "0.3",
      trackingNormal: "0.02em",
    },
  },
  {
    id: "modern",
    name: "Современный",
    description: "Чистый современный дизайн с четкими линиями",
    light: {
      colors: {
        background: "#ffffff",
        foreground: "#0a0a0a",
        card: "#ffffff",
        cardForeground: "#0a0a0a",
        popover: "#ffffff",
        popoverForeground: "#0a0a0a",
        primary: "#18181b",
        primaryForeground: "#fafafa",
        secondary: "#f4f4f5",
        secondaryForeground: "#18181b",
        muted: "#f4f4f5",
        mutedForeground: "#71717a",
        accent: "#f4f4f5",
        accentForeground: "#18181b",
        destructive: "#ef4444",
        destructiveForeground: "#fafafa",
        positive: "#22c55e",
        positiveForeground: "#fafafa",
        average: "#f59e0b",
        averageForeground: "#fafafa",
        height: "#3b82f6",
        heightForeground: "#fafafa",
        border: "#e4e4e7",
        input: "#e4e4e7",
        ring: "#18181b",
        chart1: "#18181b",
        chart2: "#3f3f46",
        chart3: "#71717a",
        chart4: "#a1a1aa",
        chart5: "#d4d4d8",
      },
      radius: "0.5rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "3px",
      shadowSpread: "0px",
      shadowOpacity: "0.1",
      trackingNormal: "0px",
    },
    dark: {
      colors: {
        background: "#0a0a0a",
        foreground: "#fafafa",
        card: "#0a0a0a",
        cardForeground: "#fafafa",
        popover: "#0a0a0a",
        popoverForeground: "#fafafa",
        primary: "#fafafa",
        primaryForeground: "#18181b",
        secondary: "#27272a",
        secondaryForeground: "#fafafa",
        muted: "#27272a",
        mutedForeground: "#a1a1aa",
        accent: "#27272a",
        accentForeground: "#fafafa",
        destructive: "#7f1d1d",
        destructiveForeground: "#fafafa",
        positive: "#14532d",
        positiveForeground: "#fafafa",
        average: "#78350f",
        averageForeground: "#fafafa",
        height: "#1e3a8a",
        heightForeground: "#fafafa",
        border: "#27272a",
        input: "#27272a",
        ring: "#d4d4d8",
        chart1: "#fafafa",
        chart2: "#d4d4d8",
        chart3: "#a1a1aa",
        chart4: "#71717a",
        chart5: "#52525b",
      },
      radius: "0.5rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "3px",
      shadowSpread: "0px",
      shadowOpacity: "0.1",
      trackingNormal: "0px",
    },
  },
  {
    id: "soft",
    name: "Мягкий",
    description: "Пастельные тона и плавные переходы",
    light: {
      colors: {
        background: "#fef7f6",
        foreground: "#5a4a42",
        card: "#ffffff",
        cardForeground: "#5a4a42",
        popover: "#ffffff",
        popoverForeground: "#5a4a42",
        primary: "#e2a89c",
        primaryForeground: "#ffffff",
        secondary: "#f5e6e8",
        secondaryForeground: "#5a4a42",
        muted: "#f9f0ef",
        mutedForeground: "#8b7a72",
        accent: "#d4c4e0",
        accentForeground: "#5a4a42",
        destructive: "#e89b9b",
        destructiveForeground: "#ffffff",
        positive: "#9be8b0",
        positiveForeground: "#ffffff",
        average: "#f4d89b",
        averageForeground: "#5a4a42",
        height: "#9bb0e8",
        heightForeground: "#ffffff",
        border: "#e8d6d3",
        input: "#ffffff",
        ring: "#e2a89c",
        chart1: "#e2a89c",
        chart2: "#d4c4e0",
        chart3: "#9be8b0",
        chart4: "#f4d89b",
        chart5: "#9bb0e8",
      },
      radius: "1rem",
      shadowX: "0px",
      shadowY: "2px",
      shadowBlur: "8px",
      shadowSpread: "0px",
      shadowOpacity: "0.05",
      trackingNormal: "0.3px",
    },
    dark: {
      colors: {
        background: "#2a2423",
        foreground: "#f5e6e8",
        card: "#3a3332",
        cardForeground: "#f5e6e8",
        popover: "#3a3332",
        popoverForeground: "#f5e6e8",
        primary: "#e2a89c",
        primaryForeground: "#2a2423",
        secondary: "#4a3f3d",
        secondaryForeground: "#f5e6e8",
        muted: "#3f3735",
        mutedForeground: "#c4b4b0",
        accent: "#9b8aa8",
        accentForeground: "#f5e6e8",
        destructive: "#c87575",
        destructiveForeground: "#ffffff",
        positive: "#75c88a",
        positiveForeground: "#ffffff",
        average: "#d4b575",
        averageForeground: "#2a2423",
        height: "#7590c8",
        heightForeground: "#ffffff",
        border: "#4a3f3d",
        input: "#3a3332",
        ring: "#e2a89c",
        chart1: "#e2a89c",
        chart2: "#9b8aa8",
        chart3: "#75c88a",
        chart4: "#d4b575",
        chart5: "#7590c8",
      },
      radius: "1rem",
      shadowX: "0px",
      shadowY: "2px",
      shadowBlur: "8px",
      shadowSpread: "0px",
      shadowOpacity: "0.05",
      trackingNormal: "0.3px",
    },
  },
  {
    id: "monochrome",
    name: "Монохром",
    description: "Минималистичная черно-белая тема",
    light: {
      colors: {
        background: "#ffffff",
        foreground: "#000000",
        card: "#fafafa",
        cardForeground: "#000000",
        popover: "#fafafa",
        popoverForeground: "#000000",
        primary: "#000000",
        primaryForeground: "#ffffff",
        secondary: "#e5e5e5",
        secondaryForeground: "#000000",
        muted: "#f5f5f5",
        mutedForeground: "#666666",
        accent: "#333333",
        accentForeground: "#ffffff",
        destructive: "#000000",
        destructiveForeground: "#ffffff",
        positive: "#4a4a4a",
        positiveForeground: "#ffffff",
        average: "#7a7a7a",
        averageForeground: "#ffffff",
        height: "#2a2a2a",
        heightForeground: "#ffffff",
        border: "#e0e0e0",
        input: "#ffffff",
        ring: "#000000",
        chart1: "#000000",
        chart2: "#333333",
        chart3: "#666666",
        chart4: "#999999",
        chart5: "#cccccc",
      },
      radius: "0.25rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "2px",
      shadowSpread: "0px",
      shadowOpacity: "0.05",
      trackingNormal: "0em",
    },
    dark: {
      colors: {
        background: "#000000",
        foreground: "#ffffff",
        card: "#0a0a0a",
        cardForeground: "#ffffff",
        popover: "#0a0a0a",
        popoverForeground: "#ffffff",
        primary: "#ffffff",
        primaryForeground: "#000000",
        secondary: "#2a2a2a",
        secondaryForeground: "#ffffff",
        muted: "#1a1a1a",
        mutedForeground: "#999999",
        accent: "#cccccc",
        accentForeground: "#000000",
        destructive: "#ffffff",
        destructiveForeground: "#000000",
        positive: "#b5b5b5",
        positiveForeground: "#000000",
        average: "#858585",
        averageForeground: "#000000",
        height: "#d5d5d5",
        heightForeground: "#000000",
        border: "#333333",
        input: "#0a0a0a",
        ring: "#ffffff",
        chart1: "#ffffff",
        chart2: "#cccccc",
        chart3: "#999999",
        chart4: "#666666",
        chart5: "#333333",
      },
      radius: "0.25rem",
      shadowX: "0px",
      shadowY: "1px",
      shadowBlur: "2px",
      shadowSpread: "0px",
      shadowOpacity: "0.1",
      trackingNormal: "0em",
    },
  },
  {
    id: "sketchy",
    name: "Скетч",
    description: "Рисованный стиль с мягкими тенями",
    light: {
      colors: {
        background: "#f9f9f9",
        foreground: "#3a3a3a",
        card: "#ffffff",
        cardForeground: "#3a3a3a",
        popover: "#ffffff",
        popoverForeground: "#3a3a3a",
        primary: "#606060",
        primaryForeground: "#f0f0f0",
        secondary: "#dedede",
        secondaryForeground: "#3a3a3a",
        muted: "#e3e3e3",
        mutedForeground: "#505050",
        accent: "#f3eac8",
        accentForeground: "#5d4037",
        destructive: "#c87a7a",
        destructiveForeground: "#ffffff",
        positive: "#7ac89b",
        positiveForeground: "#ffffff",
        average: "#f4c542",
        averageForeground: "#3a3a3a",
        height: "#7a9ec8",
        heightForeground: "#ffffff",
        border: "#747272",
        input: "#ffffff",
        ring: "#a0a0a0",
        chart1: "#333333",
        chart2: "#555555",
        chart3: "#777777",
        chart4: "#999999",
        chart5: "#bbbbbb",
      },
      radius: "0.625rem",
      shadowX: "1px",
      shadowY: "4px",
      shadowBlur: "5px",
      shadowSpread: "0px",
      shadowOpacity: "0.03",
      trackingNormal: "0.5px",
    },
    dark: {
      colors: {
        background: "#2b2b2b",
        foreground: "#dcdcdc",
        card: "#333333",
        cardForeground: "#dcdcdc",
        popover: "#333333",
        popoverForeground: "#dcdcdc",
        primary: "#b0b0b0",
        primaryForeground: "#2b2b2b",
        secondary: "#5a5a5a",
        secondaryForeground: "#c0c0c0",
        muted: "#454545",
        mutedForeground: "#a0a0a0",
        accent: "#e0e0e0",
        accentForeground: "#333333",
        destructive: "#d9afaf",
        destructiveForeground: "#2b2b2b",
        positive: "#afd9bf",
        positiveForeground: "#2b2b2b",
        average: "#f4d57a",
        averageForeground: "#2b2b2b",
        height: "#afc0d9",
        heightForeground: "#2b2b2b",
        border: "#4f4f4f",
        input: "#333333",
        ring: "#c0c0c0",
        chart1: "#efefef",
        chart2: "#d0d0d0",
        chart3: "#b0b0b0",
        chart4: "#909090",
        chart5: "#707070",
      },
      radius: "0.625rem",
      shadowX: "1px",
      shadowY: "4px",
      shadowBlur: "5px",
      shadowSpread: "0px",
      shadowOpacity: "0.03",
      trackingNormal: "0.5px",
    },
  },
];
