import { StoreFilters } from "@pages/stores/model/types";

export const EMPTY_STORE_FILTERS: StoreFilters = {
  idStore: [],
  idCity: [],
  idRegion: [],
  idManager: [],
  ageGroup: [],
  idLegalEntity: [],
  channel: [],
  district: [],
  storeCondition: [],
  nightStore: null,
  shopOnAuto: null,
  deliveryIm: null,
  walkingDelivery: null,
  grill: null,
  dopeki: null,
  bakehouse: null,
  brazier: null,
  camera: null,
  coffee: null,
  typeCoffee: [],
  ownershipCoffee: [],
  milkRefrigerator: null,
  pizzaCm: [],
  pizzaDaysSchedule: [],
  pizzaHoursSchedule: [],
  maxPower: [],
  format: [],
  discountTime: [],
  startDate: "1800-01-01",
  endDate: "2030-06-10",
};
