export const graphic_sales = [
  {
    name: "Выбранный период",
    data: [
      ["2025-04-01", 175342],
      ["2025-04-02", 202322],
      ["2025-04-03", 196954],
      ["2025-04-04", 236629],
      ["2025-04-05", 184858],
      ["2025-04-06", 116713],
      ["2025-04-07", 185118],
      ["2025-04-08", 164472],
      ["2025-04-09", 191847],
      ["2025-04-10", 239248],
      ["2025-04-11", 244015],
      ["2025-04-12", 215475],
      ["2025-04-13", 176378],
      ["2025-04-14", 198543],
      ["2025-04-15", 208264],
      ["2025-04-16", 217762],
      ["2025-04-17", 246671],
      ["2025-04-18", 318839],
      ["2025-04-19", 268980],
      ["2025-04-20", 128650],
      ["2025-04-21", 154089],
      ["2025-04-22", 169166],
    ],
  },
  {
    name: "Прошлый год",
    data: [
      ["2025-04-01", 185710],
      ["2025-04-02", 215324],
      ["2025-04-03", 211405],
      ["2025-04-04", 234014],
      ["2025-04-05", 253916],
      ["2025-04-06", 236730],
      ["2025-04-07", 140648],
      ["2025-04-08", 217014],
      ["2025-04-09", 195450],
      ["2025-04-10", 201894],
      ["2025-04-11", 272650],
      ["2025-04-12", 245849],
      ["2025-04-13", 206735],
      ["2025-04-14", 146845],
      ["2025-04-15", 201533],
      ["2025-04-16", 244001],
      ["2025-04-17", 224217],
      ["2025-04-18", 251325],
      ["2025-04-19", 328884],
      ["2025-04-20", 227271],
      ["2025-04-21", 143725],
      ["2025-04-22", 194448],
    ],
  },
];

export const graphic_check = [
  {
    name: "Выбранный период",
    data: [
      ["2025-04-01", 365],
      ["2025-04-02", 404],
      ["2025-04-03", 375],
      ["2025-04-04", 448],
      ["2025-04-05", 309],
      ["2025-04-06", 231],
      ["2025-04-07", 385],
      ["2025-04-08", 366],
      ["2025-04-09", 385],
      ["2025-04-10", 421],
      ["2025-04-11", 423],
      ["2025-04-12", 326],
      ["2025-04-13", 280],
      ["2025-04-14", 392],
      ["2025-04-15", 411],
      ["2025-04-16", 436],
      ["2025-04-17", 441],
      ["2025-04-18", 529],
      ["2025-04-19", 380],
      ["2025-04-20", 213],
      ["2025-04-21", 334],
      ["2025-04-22", 368],
    ],
  },
  {
    name: "Прошлый год",
    data: [
      ["2025-04-01", 396],
      ["2025-04-02", 444],
      ["2025-04-03", 451],
      ["2025-04-04", 480],
      ["2025-04-05", 521],
      ["2025-04-06", 390],
      ["2025-04-07", 289],
      ["2025-04-08", 483],
      ["2025-04-09", 407],
      ["2025-04-10", 431],
      ["2025-04-11", 515],
      ["2025-04-12", 482],
      ["2025-04-13", 358],
      ["2025-04-14", 274],
      ["2025-04-15", 403],
      ["2025-04-16", 513],
      ["2025-04-17", 465],
      ["2025-04-18", 480],
      ["2025-04-19", 560],
      ["2025-04-20", 377],
      ["2025-04-21", 280],
      ["2025-04-22", 419],
    ],
  },
];

export const tbl_total = [
  { storename: "Итого", proceeds: 4440335, proceedsMoM: 181899 },
];

export const tbl = [
  {
    idStore: 42025,
    storename: "Кемерово, Шахтеров пр, 36",
    proceeds: 4440335,
    proceedsMoM: 181899,
  },
];

export const settings = {
  salesDynamics: [
    [
      {
        name: "groupProceeds",
        order: 0,
        columns: [
          { name: "proceeds", active: true },
          { name: "proceedsLM", active: true },
          { name: "proceedsMoM", active: true },
          { name: "proceedsMoMPercent", active: true },
          { name: "proceedsLY", active: true },
          { name: "proceedsYoY", active: true },
          { name: "proceedsYoYPercent", active: true },
          { name: "cumulativeProceedsTodayYear", active: true },
          { name: "cumulativeProceedsLastYear", active: true },
          { name: "cumulativeProceedsYoY", active: true },
          { name: "cumulativeProceedsYoYPercent", active: true },
        ],
      },
      {
        name: "groupPlanProceeds",
        order: 1,
        columns: [
          { name: "planProceeds", active: true },
          { name: "planProceedsExecutionPercent", active: true },
          { name: "planProceedsForecast", active: true },
          { name: "planProceedsForecastPercent", active: true },
          { name: "cumulativeProceedsPlan", active: true },
          { name: "cumulativePlanProceedsExecutionPercent", active: true },
          { name: "cumulativePlanProceedsForecastPercent", active: true },
        ],
      },
      {
        name: "groupCheck",
        order: 2,
        columns: [
          { name: "check", active: true },
          { name: "checkLM", active: true },
          { name: "checkMoM", active: true },
          { name: "checkMoMPercent", active: true },
          { name: "checkLY", active: true },
          { name: "checkYoY", active: true },
          { name: "checkYoYPercent", active: true },
          { name: "cumulativeCheckTodayYear", active: true },
          { name: "cumulativeCheckLastYear", active: true },
          { name: "cumulativeCheckYoY", active: true },
          { name: "cumulativeCheckYoYPercent", active: true },
        ],
      },
      {
        name: "groupPlanCheck",
        order: 3,
        columns: [
          { name: "planCheck", active: true },
          { name: "planCheckExecutionPercent", active: true },
          { name: "planCheckForecast", active: true },
          { name: "planCheckForecastPercent", active: true },
          { name: "cumulativeCheckPlan", active: true },
          { name: "cumulativePlanCheckExecutionPercent", active: true },
          { name: "cumulativePlanCheckForecastPercent", active: true },
        ],
      },
      {
        name: "groupAvgCheck",
        order: 4,
        columns: [
          { name: "avgCheck", active: true },
          { name: "avgCheckLM", active: true },
          { name: "avgCheckMoM", active: true },
          { name: "avgCheckMoMPercent", active: true },
          { name: "avgCheckLY", active: true },
          { name: "avgCheckYoY", active: true },
          { name: "avgCheckYoYPercent", active: true },
          { name: "cumulativeAvgCheckTodayYear", active: true },
          { name: "cumulativeAvgCheckLastYear", active: true },
          { name: "cumulativeAvgCheckYoY", active: true },
          { name: "cumulativeAvgCheckYoYPercent", active: true },
        ],
      },
      {
        name: "groupPlanAvgCheck",
        order: 5,
        columns: [
          { name: "planAvgCheck", active: true },
          { name: "planAvgCheckExecutionPercent", active: true },
          { name: "planAvgCheckForecast", active: true },
          { name: "planAvgCheckForecastPercent", active: true },
          { name: "cumulativeAvgCheckPlan", active: true },
          { name: "cumulativePlanAvgCheckExecutionPercent", active: true },
          { name: "cumulativePlanAvgCheckForecastPercent", active: true },
        ],
      },
      {
        name: "groupCheckQc",
        order: 6,
        columns: [
          { name: "proceedsQc", active: true },
          { name: "proceedsQcLM", active: true },
          { name: "proceedsQcMoM", active: true },
          { name: "proceedsQcMoMPercent", active: true },
          { name: "proceedsQcLY", active: true },
          { name: "proceedsQcYoY", active: true },
          { name: "proceedsQcYoYPercent", active: true },
          { name: "cumulativeProceedsQcTodayYear", active: true },
          { name: "cumulativeProceedsQcLastYear", active: true },
          { name: "cumulativeProceedsQcYoY", active: true },
          { name: "cumulativeProceedsQcYoYPercent", active: true },
        ],
      },
      {
        name: "groupPlanQc",
        order: 7,
        columns: [
          { name: "planProceedsQc", active: true },
          { name: "planProceedsQcExecutionPercent", active: true },
          { name: "planProceedsQcForecast", active: true },
          { name: "planProceedsQcForecastPercent", active: true },
          { name: "cumulativeProceedsQcPlan", active: true },
          { name: "cumulativePlanProceedsQcExecutionPercent", active: true },
          { name: "cumulativePlanProceedsQcForecastPercent", active: true },
        ],
      },
      {
        name: "shareOfPaymentsQc",
        order: 7,
        columns: [
          { name: "shareOfPaymentsQc", active: true },
          { name: "planShareOfPaymentsQc", active: true },
          { name: "planShareOfPaymentsQcExecutionPercent", active: true },
          { name: "planShareOfPaymentsQcForecast", active: true },
          { name: "planShareOfPaymentsQcForecastPercent", active: true },
        ],
      },
      {
        name: "groupDiscount",
        order: 8,
        columns: [
          { name: "discount", active: true },
          { name: "discountLM", active: true },
          { name: "discountMoM", active: true },
          { name: "discountMoMPercent", active: true },
          { name: "discountLY", active: true },
          { name: "discountYoY", active: true },
          { name: "discountYoYPercent", active: true },
          { name: "cumulativeDiscountTodayYear", active: true },
          { name: "cumulativeDiscountLastYear", active: true },
          { name: "cumulativeDiscountYoY", active: true },
          { name: "cumulativeDiscountYoYPercent", active: true },
        ],
      },
      {
        name: "groupDiscountPercent",
        order: 9,
        columns: [
          { name: "discountPercent", active: true },
          { name: "discountPercentLM", active: true },
          { name: "discountPercentMoMPercent", active: true },
          { name: "discountPercentLY", active: true },
          { name: "discountPercentYoYPercent", active: true },
          { name: "cumulativeDiscountPercentTodayYear", active: true },
          { name: "cumulativeDiscountPercentLastYear", active: true },
          { name: "cumulativeDiscountPercentYoYPercent", active: true },
        ],
      },
      {
        name: "groupCostPrice",
        order: 10,
        columns: [
          { name: "costPrice", active: true },
          { name: "costPriceLM", active: true },
          { name: "costPriceMoM", active: true },
          { name: "costPriceMoMPercent", active: true },
          { name: "costPriceLY", active: true },
          { name: "costPriceYoY", active: true },
          { name: "costPriceYoYPercent", active: true },
          { name: "cumulativeCostPriceTodayYear", active: true },
          { name: "cumulativeCostPriceLastYear", active: true },
          { name: "cumulativeCostPriceYoY", active: true },
          { name: "cumulativeCostPriceYoYPercent", active: true },
        ],
      },
      {
        name: "groupProfit",
        order: 11,
        columns: [
          { name: "profit", active: true },
          { name: "profitLM", active: true },
          { name: "profitMoM", active: true },
          { name: "profitMoMPercent", active: true },
          { name: "profitLY", active: true },
          { name: "profitYoY", active: true },
          { name: "profitYoYPercent", active: true },
          { name: "cumulativeProfitTodayYear", active: true },
          { name: "cumulativeProfitLastYear", active: true },
          { name: "cumulativeProfitYoY", active: true },
          { name: "cumulativeProfitYoYPercent", active: true },
        ],
      },
      {
        name: "groupWriteOff",
        order: 12,
        columns: [
          { name: "writeOff", active: true },
          { name: "writeOffLM", active: true },
          { name: "writeOffMoM", active: true },
          { name: "writeOffMoMPercent", active: true },
          { name: "writeOffLY", active: true },
          { name: "writeOffYoY", active: true },
          { name: "writeOffYoYPercent", active: true },
          { name: "cumulativeWriteOffTodayYear", active: true },
          { name: "cumulativeWriteOffLastYear", active: true },
          { name: "cumulativeWriteOffYoY", active: true },
          { name: "cumulativeWriteOffYoYPercent", active: true },
        ],
      },
      {
        name: "groupWriteOffPercent",
        order: 13,
        columns: [
          { name: "writeOffPercent", active: true },
          { name: "writeOffPercentLM", active: true },
          { name: "writeOffPercentMoMPercent", active: true },
          { name: "writeOffPercentLY", active: true },
          { name: "writeOffPercentYoYPercent", active: true },
          { name: "cumulativeWriteOffPercentTodayYear", active: true },
          { name: "cumulativeWriteOffPercentLastYear", active: true },
          { name: "cumulativeWriteOffPercentYoY", active: true },
        ],
      },
      {
        name: "groupMarginPercent",
        order: 14,
        columns: [
          { name: "marginPercent", active: true },
          { name: "marginPercentLM", active: true },
          { name: "marginPercentMoMPercent", active: true },
          { name: "marginPercentLY", active: true },
          { name: "marginPercentYoYPercent", active: true },
          { name: "cumulativeMarginPercentTodayYear", active: true },
          { name: "cumulativeMarginPercentLastYear", active: true },
          { name: "cumulativeMarginPercentYoY", active: true },
        ],
      },
      {
        name: "groupMarkupPercent",
        order: 14,
        columns: [
          { name: "markupPercent", active: true },
          { name: "markupPercentLM", active: true },
          { name: "markupPercentMoMPercent", active: true },
          { name: "markupPercentLY", active: true },
          { name: "markupPercentYoYPercent", active: true },
          { name: "cumulativeMarkupPercentTodayYear", active: true },
          { name: "cumulativeMarkupPercentLastYear", active: true },
          { name: "cumulativeMarkupPercentYoY", active: true },
        ],
      },
      {
        name: "groupSkuUnique",
        order: 14,
        columns: [
          { name: "skuUnique", active: true },
          { name: "skuUniqueLM", active: true },
          { name: "skuUniqueMoM", active: true },
          { name: "skuUniqueMoMPercent", active: true },
          { name: "skuUniqueLY", active: true },
          { name: "skuUniqueYoY", active: true },
          { name: "skuUniqueYoYPercent", active: true },
          { name: "cumulativeSkuUniqueTodayYear", active: true },
          { name: "cumulativeSkuUniqueLastYear", active: true },
          { name: "cumulativeSkuUniqueYoY", active: true },
          { name: "cumulativeSkuUniqueYoYPercent", active: true },
        ],
      },
      {
        name: "groupLenCheck",
        order: 15,
        columns: [
          { name: "lenCheck", active: true },
          { name: "lenCheckLM", active: true },
          { name: "lenCheckMoM", active: true },
          { name: "lenCheckMoMPercent", active: true },
          { name: "lenCheckLY", active: true },
          { name: "lenCheckYoY", active: true },
          { name: "lenCheckYoYPercent", active: true },
          { name: "cumulativeLenCheckTodayYear", active: true },
          { name: "cumulativeLenCheckLastYear", active: true },
          { name: "cumulativeLenCheckYoY", active: true },
          { name: "cumulativeLenCheckYoYPercent", active: true },
        ],
      },
      {
        name: "groupCountCheckQr",
        order: 16,
        columns: [
          { name: "countCheckQr", active: false },
          { name: "countCheckQrLM", active: false },
          { name: "countCheckQrMoM", active: false },
          { name: "countCheckQrMoMPercent", active: false },
          { name: "countCheckQrLY", active: false },
          { name: "countCheckQrYoY", active: false },
          { name: "countCheckQrYoYPercent", active: false },
          { name: "cumulativeCountCheckQrTodayYear", active: false },
          { name: "cumulativeCountCheckQrLastYear", active: false },
          { name: "cumulativeCountCheckQrYoY", active: false },
          { name: "cumulativeCountCheckQrYoYPercent", active: false },
        ],
      },
      {
        name: "groupAppLoyalPercent",
        order: 17,
        columns: [
          { name: "appLoyalPercent", active: false },
          { name: "appLoyalPercentLM", active: false },
          { name: "appLoyalPercentMoM", active: false },
          { name: "appLoyalPercentLY", active: false },
          { name: "appLoyalPercentYoY", active: false },
        ],
      },
      {
        name: "groupCheckLoyal",
        order: 18,
        columns: [
          { name: "checkLoyal", active: false },
          { name: "checkLoyalLM", active: false },
          { name: "checkLoyalMoM", active: false },
          { name: "checkLoyalMoMPercent", active: false },
          { name: "checkLoyalLY", active: false },
          { name: "checkLoyalYoY", active: false },
          { name: "checkLoyalYoYPercent", active: false },
        ],
      },
      {
        name: "groupProceedsIm",
        order: 19,
        columns: [
          { name: "proceedsIm", active: false },
          { name: "proceedsImLM", active: false },
          { name: "proceedsImMoM", active: false },
          { name: "proceedsImMoMPercent", active: false },
          { name: "proceedsImLY", active: false },
          { name: "proceedsImYoY", active: false },
          { name: "proceedsImYoYPercent", active: false },
        ],
      },
      {
        name: "groupOnlineStoreShare",
        order: 20,
        columns: [
          { name: "onlineStoreSharePercent", active: false },
          { name: "onlineStoreSharePercentLY", active: false },
          { name: "onlineStoreSharePercentYoY", active: false },
          { name: "onlineStoreSharePercentLM", active: false },
          { name: "onlineStoreSharePercentMoM", active: false },
        ],
      },
    ],
  ],
};
