// Маппинг ID пользователей на их персональные фразы
export const userMessages: Record<number, string[]> = {
  181: [
    // Вступление и сравнения
    "Вика, если бы красота была преступлением, ты бы уже отбывала пожизненное.",
    "Говорят, идеальных людей не существует, но потом я встретил тебя и понял, что они просто плохо искали.",
    "Моника Беллуччи нервно курит в сторонке, когда ты заходишь в комнату.",
    "Ты как редкий коллекционный экземпляр — таких больше не производят.",
    "Мой уровень серотонина взлетает до небес, стоит мне только увидеть уведомление от тебя.",

    // Глаза (Зеленые)
    "В твоих зеленых глазах столько магии... Ощущение, что меня приворожили, и я совсем не против.",
    "Твой взгляд глубже любого океана, в нем хочется утонуть и не спасаться.",
    "Есть в твоих глазах какая-то чертовщинка, которая сводит меня с ума.",
    "Никакие драгоценные камни не сверкают так ярко, как твои зеленые глаза на солнце.",
    "Один твой взгляд — и я забываю, куда шел и что хотел сказать.",

    // Волосы (Длинные, выпрямленные)
    "Твои волосы — это просто черный шелк. Знаю, сколько сил уходит на выпрямление, и этот результат того стоит!",
    "Мне кажется, у твоих волос есть суперспособность — они делают тебя похожей на диснеевскую принцессу.",
    "Обожаю пропускать твои пряди сквозь пальцы, это мой личный антистресс.",
    "Твоя прическа всегда выглядит так, будто ты только что вышла из салона. Идеально.",
    "Ты укротила свои кудряшки, а заодно укротила и мое сердце.",

    // Стиль (Розовый костюм, белая шуба, ногти)
    "Когда ты в этом розовом костюме, градус 'мимимишности' просто зашкаливает, хочется тебя затискать.",
    "Розовый цвет придумали специально для тебя, чтобы подчеркнуть твою женственность.",
    "В своей белой шубе ты выглядишь как Снежная Королева, которая растаяла только для меня.",
    "Ты в шубке выглядишь так роскошно и статно, будто владеешь половиной города.",
    "Твои руки с этим аккуратным маникюром хочется целовать бесконечно.",
    "Твой стиль — это сочетание уюта и шика. Обожаю твой вкус, даже в мелочах вроде ногтей.",
    "Ты в розовой куртке — самое яркое пятно в этом сером городе.",

    // Работа (Категорийный менеджер)
    "Если бы у всех поставщиков были такие менеджеры, как ты, экономика страны взлетела бы до небес.",
    "Самый сексуальный категорийный менеджер в истории ритейла — это точно ты.",
    "Представляю, как сложно людям с тобой спорить по работе — твоей харизме невозможно отказать.",
    "Ты — тот редкий случай, когда невероятная красота сочетается с острым умом и деловой хваткой.",
    "Горжусь тем, какая ты профи. Решать вопросики — это точно твой талант.",

    // Уют, вейп и моменты
    "Даже вкус пара твоей одноразки кажется вкуснее, когда ты рядом.",
    "Люблю наши моменты, когда мы просто курим, болтаем и никуда не спешим.",
    "Делиться с тобой вейпом — это наш маленький, но такой приятный ритуал.",
    "С тобой уютно даже просто молчать, и это бесценно.",

    // Чувства и романтика
    "Вика, ты не просто часть моей жизни, ты делаешь её полной версией.",
    "Рядом с тобой я чувствую себя героем крутого фильма, которому досталась главная красавица.",
    "Ты вызываешь у меня привыкание сильнее, чем что-либо на свете.",
    "Каждое утро благодарю судьбу (и интернет), что мы нашлись.",
    "Ты — мой личный сорт эндорфина.",
    "Люблю, когда ты улыбаешься, в этот момент мир становится чуточку добрее.",
    "Ты для меня — эталон. Серьезно, лучше просто не бывает.",
  ],
  2734: [
    "Самые красивые глаза сейчас читают эту фразу",
    "Ты умеешь появляться в мыслях ровно в тот момент, когда это нужно",
    "В тебе есть редкое умение — не обещать чудес и при этом быть маленьким чудом",
    "Ты как очень любимая песня — не надоедает, даже если слушать часто",
    "Есть ощущение, что рядом с тобой мир становится чуть внимательнее и добрее",
    "У тебя получается быть светом даже тогда, когда ты сама этого не замечаешь",
    "Ты из тех людей, с которыми даже молчание не хочется заполнять лишними словами",
    "В твоём темпе что‑то очень правильное — спокойное, но живое",
    "С тобой хочется замедлиться и наконец перестать спешить",
    "В каждом твоём “пиши, если что” слышится больше поддержки, чем в длинных речах",
    "Ты будто умеешь аккуратно собирать людей по частям, просто своим отношением",
    "В твоём голосе есть та самая интонация, после которой верится, что всё наладится",
    "Рядом с тобой даже мысли становятся мягче",
    "Ты создаёшь вокруг себя пространство, в котором не страшно быть настоящим",
    "Есть в тебе спокойная уверенность, на которую хочется опираться",
    "С тобой простые вещи кажутся чем‑то важным и тёплым",
    "Ты не пытаешься казаться особенной, и именно это делает тебя особенной",
    "Твои сообщения умеют вовремя попадать “в сердце”, даже если ты просто пишешь ерунду",
    "У тебя такая походка, что за тобой взгляд сам тянется",
    "Когда ты смеёшься, будто становится чуть тише в голове",
    "Ты умеешь быть рядом так, что становится легче даже о сложном говорить",
    "Твоя естественность — это вообще отдельный вид красоты",
    "От твоего “я с тобой” становится спокойнее, даже если всё сложно",
    "Ты как напоминание, что можно быть живым человеком, а не вечной гонкой",
    "С тобой даже случайные разговоры запоминаются надолго",
    "Мне не нужен google ведь ты - все, что я искал",
    "Ты из тех людей, после общения с которыми хочется жить чуть аккуратнее и добрее",
    "Есть ощущение, что в твоей голове живёт целый тёплый мир, и с каждым словом ты приоткрываешь к нему дверь",
    "Выходи за меня....Сын борец, дочь фигуристка..Жена домохозяйка..",
    "В твоём присутствии тревоги будто выключают звук",
    "Когда ты идёшь, кажется, что у улицы появляется главный персонаж",
    "Сбоку, в профиль, в движении — ты везде выглядишь очень притягательно",
    "Твои ключицы можно спокойно считать оружием медленного действия",
    "Твоё тело — это пример того, как можно выглядеть и притягательно, и естественно одновременно",
  ],
};

export const userPhotos: Record<number, string[]> = {
  181: [
    "https://bipbap.ru/wp-content/uploads/2021/12/0_c0916_ca31c1b9_xl.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/2d88dbaabe43aedff475801de9e3eac94ade981bae81713bcadb967b3326587e.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/4c87b584df24bdfbce427051345980e0.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/4d61a2aea3b4d67e225b5cdb0c574a7a.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/7rKj.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/8af6b7459552fd6e8bfafb823f418554.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/9RTqgyyu8sYxvcanYMZswSAxznHKCiMqrijAC63LtwsqXn8bf7Kxza3HYaMTr9rE1hakSrhbws.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/45bc835f6e776200a1c7136932d049a3.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/7141.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/371903_original.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/807371d98f04589c3f75374a093c055c2ffe97b04cefdcf705178539d59b0cba.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/7697921.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/172762640_ae48d4ee98a4d06589c5a5ca9c9d07ea_800.gif",
    "https://bipbap.ru/wp-content/uploads/2021/12/1557870400_ezgif.com-resize-1.gif",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1911.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1907.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-356.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1910.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1909.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1908.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1906.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1905.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1904.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1903.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1902.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1901.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1900.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1899.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1898.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1897.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1896.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1895.webp",
    "https://kartinki-life.ru/webp/2020/08/13/animirovannye-otkrytki-dlya-tebya-s-lubovu-ot-dushi-lubimomu-muzhchine-lubimoy-devushke-1894.webp",
  ],
};

export const tarotUsers: string[] = [
  "181",
  "2734",
  "2802",
  "2803",
  "200",
  "101",
  "107",
  "18",
  "2710",
];
